[directories]
input_dir = "input"
figures_dir = "output/figures"
statistics_dir = "output/statistics"
maintenance_dir = "output/maintenance"
tables_dir = "output/tables"

[datasets]
scopus = "F:/Scopus/"
