[paths]
input_dir = "input"
substitutions_file = "input/abbreviations.csv"
university_dir = "input/university_data"
dissertations_file = "intermed/100_dissertations.csv"
characteristics_file = "intermed/102_characteristics.csv"
dissertations_master = "intermed/290_dissertations_master"
figures_dir = "output/figures"
statistics_dir = "output/statistics"
maintenance_dir = "output/maintenance"
tables_dir = "output/tables"

[datasets]
hochschulschriften = "https://api.github.com/repos/Michael-E-Rose/Hochschulschriften/contents/80_master/"

[models]
noun_phrases = "de_core_news_lg"
